config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
root 'store#index', as: 'store_index'

  resources :bikes
namespace :admin do
root 'application#index'
resources :projects, only: [:new, :create, :destroy]
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "projects#index"

resources :projects, only: [:index, :show, :edit, :update]

end

app/models/project.rb
class Project < ApplicationRecord
validates :name, presence: true
def up
create_table :projects do |t|
t.string :name
t.string :description
t.timestamps null: false
end
end
def down
drop_table :projects
end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = 'Project has been created.'
      redirect_to @project
    else
      flash.now[:alert] = 'Project has not been created.'
      render 'new'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    flash[:notice] = 'Project has been deleted.'
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  def index
    @projects = Project.all    
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:notice] = 'Project has been updated.'
      redirect_to @project
    else
      flash.now[:alert] = 'Project has not been updated.'
      render 'edit'
    end
  end

  private
  def project_params
    params.require(:project).permit(:name, :description)
  end

  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'The project you were looking for could not be found.'
    redirect_to projects_path
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
<% if project.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(project.errors.count, "error") %>
prohibited this project from being saved:</h2>
<ul>
<% project.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<p>
<%= f.label :name %><br>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :description %><br>
<%= f.text_field :description %>
</p>
<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<header>
<h1>Edit Project</h1>
</header>
<%= render "form", project: @project %>

app/views/projects/index.html.erb
<header>
<<<<<<< HEAD
  <h1>Projects</h1>
  
=======
<h1>Projects</h1>  
>>>>>>> ef1729f3ab92c4bda25b3b4cef0921f114acf64b
  <% admins_only do %>
    <ul class="actions">
      <li><%=link_to "New Project", new_admin_project_path,
        class: "new" %></li>
    </ul>
<% end %>
</header>
<div id="projects">
<% @projects.each do |project| %>
<h2><%= link_to project.name, project %></h2>
<p><%= project.description %></p>
<% end %>
</div>

app/views/projects/new.html.erb
<header>
<h1>New Project</h1>
</header>
<%= form_for(@project) do |f| %>
<% if @project.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@project.errors.count, "error") %>
prohibited this project from being saved:</h2>
<ul>
<% @project.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<p>
<%= f.label :name %><br>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :description %><br>
<%= f.text_field :description %>
</p>
<%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<header>
<h1><%= @project.name %></h1>
<ul class="actions">
<li><%= link_to "Edit Project", edit_project_path(@project),
class: "edit" %></li>
<% admins_only do %>
<li><%= link_to "Delete Project", admin_project_path(@project),
method: :delete,
data: { confirm: "Are you sure you want to delete this project?" },
class: "delete" %></li>
<% end %>
</ul>
</header>